<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusFlow.Diagnostics\NexusFlow.Diagnostics.csproj" />
    <ProjectReference Include="..\NexusFlow.Identity\NexusFlow.Identity.csproj" />
    <ProjectReference Include="..\NexusFlow.Protocol\NexusFlow.Protocol.csproj" />
  </ItemGroup>

</Project>
