<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NexusFlow.Core\NexusFlow.Core.csproj" />
    <ProjectReference Include="..\..\src\NexusFlow.Identity\NexusFlow.Identity.csproj" />
    <ProjectReference Include="..\..\src\NexusFlow.Input\NexusFlow.Input.csproj" />
    <ProjectReference Include="..\..\src\NexusFlow.Diagnostics\NexusFlow.Diagnostics.csproj" />
    <ProjectReference Include="..\..\src\NexusFlow.Protocol\NexusFlow.Protocol.csproj" />
    <ProjectReference Include="..\..\src\NexusFlow.Routing\NexusFlow.Routing.csproj" />
    <ProjectReference Include="..\..\src\NexusFlow.Settings\NexusFlow.Settings.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
