<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\NexusFlow.Diagnostics\NexusFlow.Diagnostics.csproj" />
    <ProjectReference Include="..\NexusFlow.Identity\NexusFlow.Identity.csproj" />
    <ProjectReference Include="..\NexusFlow.Protocol\NexusFlow.Protocol.csproj" />
    <ProjectReference Include="..\NexusFlow.Settings\NexusFlow.Settings.csproj" />
  </ItemGroup>

</Project>
